window.runAppTests = async function (assert) {
  function el(id) { return document.getElementById(id); }
  function key(code) { document.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, keyCode: code })); }
  function message(text) { addChatMessage({ content: text, sender: { username: 'Viewer', identity: { color: '#000044', badges: [{ type: 'subscriber' }] } } }); }
  function pointer(target, type, x, y, buttons) {
    target.dispatchEvent(new PointerEvent(type, { bubbles: true, cancelable: true, clientX: x, clientY: y,
      button: 0, buttons: buttons, pointerId: 1, pointerType: 'mouse', isPrimary: true }));
  }
  var favorites = getFavorites(); favorites.push('should-not-persist');
  assert(getFavorites().length === 2, 'favorites cache returns an isolated list');
  assert(isFavorite('alpha') && !isFavorite('missing'), 'favorite membership uses the same cached state');
  addFavorite('gamma'); assert(getFavorites().indexOf('gamma') !== -1, 'adding invalidates favorites cache');
  removeFavorite('gamma'); assert(getFavorites().indexOf('gamma') === -1, 'removing invalidates favorites cache');
  renderSidebar();
  var originalSidebar = renderSidebar, sidebarRenders = 0;
  renderSidebar = function () { sidebarRenders++; return originalSidebar.apply(this, arguments); };
  openSidebar();
  assert(sidebarRenders === 0 && el('sidebar').classList.contains('open'), 'prepared sidebar opens before secondary render work');
  await fixtureWait();
  assert(sidebarRenders === 1, 'sidebar secondary work runs after its first paint');
  closeSidebar(); renderSidebar = originalSidebar;
  var previewPositions = 0;
  var preview = makePreviewCard('sidepreview', function () { return 'beta'; }, function () { previewPositions++; });
  preview.update();
  assert(previewPositions === 0, 'preview focus avoids immediate measurement or positioning');
  preview.cancel(); await fixtureWait(230);
  assert(previewPositions === 0, 'leaving focus cancels delayed preview work');
  var validPreview = true;
  preview = makePreviewCard('sidepreview', function () { return validPreview ? 'beta' : null; }, function () { previewPositions++; });
  preview.update(); validPreview = false; await fixtureWait(230);
  validPreview = true; preview.update(); await fixtureWait(230);
  assert(previewPositions > 0, 'preview can resume the same identity after modal invalidates dwell');
  preview.cancel();
  saveSettings();
  var globalWrites = fixtureWrites['kicktv.settings'] || 0, profileWrites = fixtureWrites[CHAT_PREF_KEY] || 0;
  saveSettings(); saveSettings();
  assert(fixtureWrites['kicktv.settings'] === globalWrites, 'unchanged global settings avoid storage writes');
  assert((fixtureWrites[CHAT_PREF_KEY] || 0) === profileWrites, 'unchanged chat profiles avoid serialization and storage writes');
  settings.lowlatency = !settings.lowlatency; saveSettings();
  assert((fixtureWrites[CHAT_PREF_KEY] || 0) === profileWrites, 'global changes do not rewrite chat profiles');
  assert(settings.chat === false, 'chat starts disabled for a new streamer');
  settings.chat = true; settings.chatDelay = 3; settings.chatResizePreview = false; saveSettings();
  state.current = 'beta'; applyStreamerChatPreferences();
  assert(!settings.chat && settings.chatDelay === 0 && settings.chatResizePreview, 'another streamer retains default-off chat and independent defaults');
  state.current = 'alpha'; applyStreamerChatPreferences();
  assert(settings.chat && settings.chatDelay === 3 && !settings.chatResizePreview, 'all chat options restore per streamer');
  settings.chatDelay = 0; settings.chatEmotes = 'text'; settings.chatResizePreview = true;
  syncChat();
  message('<img id="injection"> [emote:1:Smile]');
  assert(chatMessagesEl().children.length === 0, 'chat waits for a frame before building DOM');
  await fixtureUntil(function () { return chatMessagesEl().children.length > 0; });
  assert(!el('injection') && chatMessagesEl().textContent.indexOf('Smile') !== -1, 'chat treats message markup as text and preserves text emotes');
  assert(!!chatMessagesEl().querySelector('.cbadge.sub'), 'batched chat preserves badges');
  for (var i = 0; i < 400; i++) message('message ' + i);
  assert(chatRenderQueue.length === 160, 'chat render backlog has a hard bound');
  await fixtureUntil(function () { return chatRenderQueue.length === 0; });
  assert(chatMessagesEl().children.length === 160 && chatMessagesEl().textContent.indexOf('message 399') !== -1, 'chat drains in order and prunes once per batch to 160 messages');
  chatEl().dispatchEvent(new Event('mouseenter'));
  el('chat-scroll').scrollTop = 0; el('chat-scroll').dispatchEvent(new Event('scroll'));
  assert(ChatWindow.reading(), 'scrolling back pauses live following');
  chatEl().dispatchEvent(new Event('mouseleave'));
  await fixtureWait(5150);
  assert(!ChatWindow.reading() && el('chat-scroll').scrollTop > 0, 'unfocused chat returns to live after five seconds');
  settings.chatDelay = 1;
  queueChatMessage({ content: 'delayed-fixture', sender: { username: 'Viewer' } });
  await fixtureWait(100);
  assert(chatMessagesEl().textContent.indexOf('delayed-fixture') === -1, 'message delay still postpones batched messages');
  await fixtureWait(1100);
  assert(chatMessagesEl().lastChild.textContent.indexOf('delayed-fixture') !== -1, 'delayed message reaches render queue in order');
  settings.chatDelay = 0;
  browse.open = true;
  var before = chatMessagesEl().textContent;
  for (i = 0; i < 200; i++) message('covered ' + i);
  await fixtureWait();
  assert(chatMessagesEl().textContent === before && chatRenderQueue.length === 160, 'covered chat buffers a bounded tail without DOM work');
  browse.open = false; flushChatRender(); await fixtureWait(180);
  assert(chatMessagesEl().lastChild.textContent.indexOf('covered 199') !== -1, 'uncovered chat restores latest buffered messages');
  message('discard-on-switch'); disconnectChat(); await fixtureWait();
  assert(chatRenderQueue.length === 0 && chatMessagesEl().children.length === 0, 'disconnect cancels queued chat DOM work');
  settings.chat = true; syncChat();
  var r = chatEl().getBoundingClientRect();
  pointer(chatEl(), 'pointerdown', r.left + 70, r.top + 30, 1);
  pointer(document, 'pointermove', r.left - 130, 450, 1); await fixtureWait();
  pointer(document, 'pointerup', r.left - 130, 450, 0);
  r = chatEl().getBoundingClientRect();
  settings.subtitleSafe = true; ChatWindow.paint();
  assert(chatEl().getBoundingClientRect().top === r.top, 'obsolete subtitle preference does not move floating chat');
  r = chatEl().getBoundingClientRect();
  pointer(chatEl(), 'pointerdown', r.left + 70, r.top + 30, 1);
  pointer(document, 'pointermove', 20, r.top + 30, 1); await fixtureWait();
  pointer(document, 'pointerup', 20, r.top + 30, 0);
  assert(chatEl().getAttribute('data-dock') === 'left' && chatEl().getBoundingClientRect().height === 1080, 'dragging docks chat along the full left edge');
  settings.chatSeparate = true; applyChatStyle();
  r = chatEl().getBoundingClientRect();
  var videoWidth = el('video').style.width;
  pointer(el('chat-divider'), 'pointerdown', r.right - 7, 500, 1);
  pointer(document, 'pointermove', r.right + 93, 500, 1); await fixtureWait();
  assert(el('video').style.width === videoWidth && chatEl().getBoundingClientRect().width === r.width, 'outline resize keeps chat and video geometry stable during drag');
  assert(!el('chat-snap').classList.contains('hidden') && el('chat-snap').getAttribute('data-label') === 'Release to resize', 'outline shows the pending dock width');
  pointer(document, 'pointerup', r.right + 93, 500, 0);
  assert(chatEl().getBoundingClientRect().width === r.width + 100 && el('video').style.width !== videoWidth, 'releasing commits dock and video geometry together');
  assert(chatEl().getBoundingClientRect().height === 1080, 'obsolete subtitle preference does not shrink edge docking');
  settings.chat = false; syncChat();
  openSettings();
  var rows = Array.prototype.slice.call(el('settings-list').children);
  settingsMove(1);
  assert(rows.every(function (row, idx) { return el('settings-list').children[idx] === row; }), 'settings focus changes preserve every row node');
  assert(el('settings-list').querySelectorAll('.focused').length === 1, 'settings has one focused row');
  assert(rows[0].classList.contains('srow'), 'settings rows retain their base styles');
  assert(el('settings-desc').classList.contains('hidden'), 'setting descriptions wait for focus dwell');
  await fixtureWait(300);
  assert(!el('settings-desc').classList.contains('hidden'), 'description appears after dwell');
  var textItem = settings.items.filter(function (it) { return it.key === 'uiText'; })[0];
  cycleChoice(textItem);
  assert(document.body.classList.contains('ui-text-large'), 'text size choice applies to UI');
  openChatOpt();
  assert(el('ui-chat-name').textContent === 'Alpha' && el('chatopt-note').textContent.indexOf('Alpha') !== -1, 'chat settings show streamer identity and retain bottom warning');
  closeChatOpt(); openDimOpt();
  var dimRows = Array.prototype.slice.call(el('dimopt-list').children); dimoptMove(1);
  assert(dimRows.every(function (row, idx) { return el('dimopt-list').children[idx] === row; }), 'dim focus changes preserve row nodes');
  dimRows[2].dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
  assert(el('dimopt-list').children[2] === dimRows[2] && dimopt.focus === 2, 'pointer dim focus also preserves row nodes');
  closeDimOpt(); closeSettings(); openQualityOpt();
  qualityopt.items = [{ label: 'Auto', v: 'auto' }, { label: '720p', v: 720 }]; qualityopt.focus = 0; renderQualityOpt();
  var qualityRowsBefore = Array.prototype.slice.call(el('qualityopt-list').children); qualityoptMove(1);
  assert(qualityRowsBefore.every(function (row, idx) { return el('qualityopt-list').children[idx] === row; }), 'quality focus changes preserve row nodes');
  qualityRowsBefore[0].dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
  assert(el('qualityopt-list').children[0] === qualityRowsBefore[0] && qualityopt.focus === 0, 'pointer quality focus preserves row nodes');
  closeQualityOpt();
  state.current = null; state.vod = { slug: 'alpha', key: 'alpha:test', name: 'Alpha', title: 'Past stream', progressReady: true, resumeApplied: true, knownDuration: 1000 };
  Object.defineProperty(el('video'), 'duration', { configurable: true, value: 1000 }); el('video').currentTime = 123;
  saveVodProgress(true); var progressWrites = fixtureWrites[VOD_PROGRESS_KEY];
  saveVodProgress(true);
  assert(fixtureWrites[VOD_PROGRESS_KEY] === progressWrites, 'unchanged forced VOD checkpoints do not rewrite progress');
  el('video').currentTime = 145; saveVodProgress(true);
  assert(savedVodPosition('alpha:test') === 145 && fixtureWrites[VOD_PROGRESS_KEY] === progressWrites + 1, 'seek checkpoint saves changed position');
  drawVodBar(145, 1000);
  var mutations = [], observer = new MutationObserver(function (changes) { mutations = mutations.concat(changes); });
  observer.observe(el('vodbar'), { subtree: true, attributes: true, childList: true, characterData: true });
  drawVodBar(145, 1000); await fixtureWait(); observer.disconnect();
  assert(mutations.length === 0, 'unchanged timeline avoids all DOM mutations');
  requestVodOverlay(); requestVodOverlay(); requestVodOverlay();
  assert(vodOverlayFrame !== null, 'pointer VOD controls share one pending frame');
  await fixtureWait(); assert(vodBarVisible(), 'coalesced VOD reveal displays controls');
  key(461); assert(!vodBarVisible() && !state.sidebarOpen, 'first Back hides VOD controls');
  key(461); assert(state.sidebarOpen, 'next Back opens channel list');
  key(461); assert(state.sidebarOpen && state.quitArmed, 'Back again arms the exit, as it does over live');
  closeSidebar(); state.quitArmed = false; openSidebar();
  await fixtureWait(); requestVodOverlay(); key(461); await fixtureWait();
  assert(!state.sidebarOpen && !vodBarVisible(), 'Back cancels queued VOD pointer paint instead of reopening controls');
  closeSidebar(); state.vod = null; state.current = 'alpha';
  openSettings();
  await fixtureWait(300);
};
